In [51]:
import pandas as pd


csv_path = "subject-3.csv"

trial_data = pd.read_csv(csv_path)

In [52]:
trial_data_gezeigt = trial_data[trial_data["skip_trial"] == 0]
display(trial_data_gezeigt)

,AN,Code,RN,acc,accuracy,an_found,an_height,an_line,an_text,an_width,...,title,total_correct,total_response_time,total_responses,trial_counter,width,word,word_height,word_spacing,word_width
7,<AN>Frauen</AN>,C2,<RN>Experten</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,1,1920,bewertet.,53.0,25.0,197.0
15,<AN>Frauen</AN>,C6,<RN>Polizist*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,2,1920,verhandelt.,53.0,25.0,244.0
16,<AN>Frauen</AN>,C2,<RN>Einwohner</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,3,1920,Reaktionen.,53.0,25.0,242.0
20,<AN>Männer</AN>,C5,<RN>Aktivist*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,4,1920,geprüft.,53.0,25.0,175.0
31,<AN>Männer</AN>,C5,<RN>Arbeitnehmer*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,5,1920,offen.,53.0,25.0,129.0
34,<AN>Frauen</AN>,C4,<RN>Krankenschwestern</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,6,1920,diskutiert.,53.0,25.0,243.0
36,<AN>Frauen</AN>,C4,<RN>Expertinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,7,1920,geprüft.,53.0,25.0,175.0
38,<AN>Männer</AN>,C5,<RN>Ingenieur*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,8,1920,diskutiert.,53.0,25.0,243.0
40,<AN>Männer</AN>,C3,<RN>Professorinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,9,1920,diskutiert.,53.0,25.0,243.0
43,<AN>Männer</AN>,C3,<RN>Dozentinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,10,1920,an.,53.0,25.0,59.0
47,<AN>Männern</AN>,C1,<RN>Einwohner</RN>,undefined,undefined,True,53.0,4.0,<AN>Männern</AN>,158.0,...,Experiment,0,0,0,11,1920,Debatten.,53.0,25.0,197.0
80,<AN>Männer</AN>,C3,<RN>Ingenieurinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,12,1920,gestritten.,53.0,25.0,244.0
94,<AN>Frauen</AN>,C4,<RN>Unternehmerinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,13,1920,umstritten.,53.0,25.0,243.0
95,<AN>Männer</AN>,C1,<RN>Experten</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,14,1920,bewertet.,53.0,25.0,197.0
96,<AN>Frauen</AN>,C2,<RN>Pfleger</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,15,1920,diskutiert.,53.0,25.0,243.0
100,<AN>Frauen</AN>,C6,<RN>Arbeitnehmer*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,16,1920,Diskussionen.,53.0,25.0,289.0
101,<AN>Männer</AN>,C1,<RN>Studenten</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,17,1920,Debatten.,53.0,25.0,197.0
106,<AN>Frauen</AN>,C6,<RN>Lehrer*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,18,1920,Diskussionen.,53.0,25.0,289.0

In [56]:
# Nur gezeigte Trials
trial_data_gezeigt = trial_data[trial_data["skip_trial"] == 0]

# Gewünschte Spalten
spalten = [
    "Code","AN", "RN",
    "an_found", "an_height", "an_line", "an_text", "an_width",
    "an_x1", "an_x2",
    "current_line", "current_line_width",
    "datetime",
    "display_sentence",
    "experiment_file", "experiment_path",
    "item",
    "name",
    "rn_found", "rn_height", "rn_line", "rn_text",
    "rn_width", "rn_x1", "rn_x2", "rn_y1", "rn_y2",
    "selected_list",
    "sentence",
    "skip_trial",
    "spill_x1", "spill_x2", "spill_y1", "spill_y2",
    "trial_counter"
]

# Tabelle erzeugen
trial_data_auswahl = trial_data_gezeigt[spalten]

display(trial_data_auswahl)

,Code,AN,RN,an_found,an_height,an_line,an_text,an_width,an_x1,an_x2,...,rn_y1,rn_y2,selected_list,sentence,skip_trial,spill_x1,spill_x2,spill_y1,spill_y2,trial_counter
7,C2,<AN>Frauen</AN>,<RN>Experten</RN>,True,53.0,4.0,<AN>Frauen</AN>,132.0,-223.0,-91.0,...,-56.0,-3.0,1,Auf einer öffentlichen Veranstaltung stehen In...,0,-91.0,41.0,61.0,114.0,1
15,C6,<AN>Frauen</AN>,<RN>Polizist*innen</RN>,True,53.0,4.0,<AN>Frauen</AN>,132.0,-202.0,-70.0,...,-173.0,-120.0,1,Bei einer öffentlichen Sitzung im Rathaus wird...,0,-70.0,62.0,61.0,114.0,2
16,C2,<AN>Frauen</AN>,<RN>Einwohner</RN>,True,53.0,4.0,<AN>Frauen</AN>,132.0,-179.0,-47.0,...,-56.0,-3.0,1,Im Rahmen einer öffentlichen Veranstaltung wir...,0,-47.0,85.0,61.0,114.0,3
20,C5,<AN>Männer</AN>,<RN>Aktivist*innen</RN>,True,53.0,4.0,<AN>Männer</AN>,135.0,-201.0,-66.0,...,-173.0,-120.0,1,Auf einer öffentlichen Veranstaltung werden ak...,0,-66.0,69.0,61.0,114.0,4
31,C5,<AN>Männer</AN>,<RN>Arbeitnehmer*innen</RN>,True,53.0,4.0,<AN>Männer</AN>,135.0,-220.0,-85.0,...,-56.0,-3.0,1,Im Rahmen einer Geschäftsveranstaltung findet ...,0,-85.0,50.0,61.0,114.0,5
34,C4,<AN>Frauen</AN>,<RN>Krankenschwestern</RN>,True,53.0,4.0,<AN>Frauen</AN>,132.0,-131.0,1.0,...,-173.0,-120.0,1,Bei einer Informationsveranstaltung im Kranken...,0,1.0,133.0,61.0,114.0,6
36,C4,<AN>Frauen</AN>,<RN>Expertinnen</RN>,True,53.0,4.0,<AN>Frauen</AN>,132.0,-63.0,69.0,...,-56.0,-3.0,1,Im Rahmen einer universitären Veranstaltung we...,0,69.0,201.0,61.0,114.0,7
38,C5,<AN>Männer</AN>,<RN>Ingenieur*innen</RN>,True,53.0,4.0,<AN>Männer</AN>,135.0,365.0,500.0,...,-56.0,-3.0,1,Im Rahmen einer städtischen Planungsrunde wird...,0,500.0,635.0,61.0,114.0,8
40,C3,<AN>Männer</AN>,<RN>Professorinnen</RN>,True,53.0,4.0,<AN>Männer</AN>,135.0,-65.0,70.0,...,-173.0,-120.0,1,Im Rahmen einer öffentlichen Veranstaltung wir...,0,70.0,205.0,61.0,114.0,9
43,C3,<AN>Männer</AN>,<RN>Dozentinnen</RN>,True,53.0,4.0,<AN>Männer</AN>,135.0,-339.0,-204.0,...,-173.0,-120.0,1,Auf einer schulischen Tagung werden aktuelle K...,0,-204.0,-69.0,61.0,114.0,10
47,C1,<AN>Männern</AN>,<RN>Einwohner</RN>,True,53.0,4.0,<AN>Männern</AN>,158.0,-309.0,-151.0,...,-56.0,-3.0,1,Im Rahmen einer öffentlichen Veranstaltung wir...,0,-151.0,7.0,61.0,114.0,11
80,C3,<AN>Männer</AN>,<RN>Ingenieurinnen</RN>,True,53.0,4.0,<AN>Männer</AN>,135.0,-130.0,5.0,...,-56.0,-3.0,1,Auf einer wissenschaftlichen Konferenz zu tech...,0,5.0,140.0,61.0,114.0,12
94,C4,<AN>Frauen</AN>,<RN>Unternehmerinnen</RN>,True,53.0,4.0,<AN>Frauen</AN>,132.0,-84.0,48.0,...,-56.0,-3.0,1,Bei einem Networking-Event stehen wirtschaftsp...,0,48.0,180.0,61.0,114.0,13
95,C1,<AN>Männer</AN>,<RN>Experten</RN>,True,53.0,4.0,<AN>Männer</AN>,135.0,-309.0,-174.0,...,-56.0,-3.0,1,Beim Sommerfest eines Unternehmens wird über w...,0,-174.0,-39.0,61.0,114.0,14
96,C2,<AN>Frauen</AN>,<RN>Pfleger</RN>,True,53.0,4.0,<AN>Frauen</AN>,132.0,-222.0,-90.0,...,-173.0,-120.0,1,Im Rahmen einer Gesprächsrunde im Gesundheitsw...,0,-90.0,42.0,61.0,114.0,15
100,C6,<AN>Frauen</AN>,<RN>Arbeitnehmer*innen</RN>,True,53.0,4.0,<AN>Frauen</AN>,132.0,-105.0,27.0,...,-56.0,-3.0,1,Auf einer Gewerkschaftsveranstaltung wird derz...,0,27.0,159.0,61.0,114.0,16
101,C1,<AN>Männer</AN>,<RN>Studenten</RN>,True,53.0,4.0,<AN>Männer</AN>,135.0,-378.0,-243.0,...,-173.0,-120.0,1,Bei einer Podiumsdiskussion an der Universität...,0,-243.0,-108.0,61.0,114.0,17
106,C6,<AN>Frauen</AN>,<RN>Lehrer*innen</RN>,True,53.0,4.0,<AN>Frauen</AN>,132.0,-333.0,-201.0,...,-173.0,-120.0,1,Auf einer Konferenz zu Bildungsfragen wird der...,0,-201.0,-69.0,61.0,114.0,18

In [57]:
# Nur gezeigte Trials
trial_data_gezeigt = trial_data[trial_data["skip_trial"] == 0]

# Tabelle erzeugen
trial_data_auswahl = trial_data_gezeigt[spalten]

# Nach Code sortieren
trial_data_auswahl = trial_data_auswahl.sort_values(by="Code")

display(trial_data_auswahl)

,Code,AN,RN,an_found,an_height,an_line,an_text,an_width,an_x1,an_x2,...,rn_y1,rn_y2,selected_list,sentence,skip_trial,spill_x1,spill_x2,spill_y1,spill_y2,trial_counter
95,C1,<AN>Männer</AN>,<RN>Experten</RN>,True,53.0,4.0,<AN>Männer</AN>,135.0,-309.0,-174.0,...,-56.0,-3.0,1,Beim Sommerfest eines Unternehmens wird über w...,0,-174.0,-39.0,61.0,114.0,14
47,C1,<AN>Männern</AN>,<RN>Einwohner</RN>,True,53.0,4.0,<AN>Männern</AN>,158.0,-309.0,-151.0,...,-56.0,-3.0,1,Im Rahmen einer öffentlichen Veranstaltung wir...,0,-151.0,7.0,61.0,114.0,11
101,C1,<AN>Männer</AN>,<RN>Studenten</RN>,True,53.0,4.0,<AN>Männer</AN>,135.0,-378.0,-243.0,...,-173.0,-120.0,1,Bei einer Podiumsdiskussion an der Universität...,0,-243.0,-108.0,61.0,114.0,17
7,C2,<AN>Frauen</AN>,<RN>Experten</RN>,True,53.0,4.0,<AN>Frauen</AN>,132.0,-223.0,-91.0,...,-56.0,-3.0,1,Auf einer öffentlichen Veranstaltung stehen In...,0,-91.0,41.0,61.0,114.0,1
96,C2,<AN>Frauen</AN>,<RN>Pfleger</RN>,True,53.0,4.0,<AN>Frauen</AN>,132.0,-222.0,-90.0,...,-173.0,-120.0,1,Im Rahmen einer Gesprächsrunde im Gesundheitsw...,0,-90.0,42.0,61.0,114.0,15
16,C2,<AN>Frauen</AN>,<RN>Einwohner</RN>,True,53.0,4.0,<AN>Frauen</AN>,132.0,-179.0,-47.0,...,-56.0,-3.0,1,Im Rahmen einer öffentlichen Veranstaltung wir...,0,-47.0,85.0,61.0,114.0,3
80,C3,<AN>Männer</AN>,<RN>Ingenieurinnen</RN>,True,53.0,4.0,<AN>Männer</AN>,135.0,-130.0,5.0,...,-56.0,-3.0,1,Auf einer wissenschaftlichen Konferenz zu tech...,0,5.0,140.0,61.0,114.0,12
43,C3,<AN>Männer</AN>,<RN>Dozentinnen</RN>,True,53.0,4.0,<AN>Männer</AN>,135.0,-339.0,-204.0,...,-173.0,-120.0,1,Auf einer schulischen Tagung werden aktuelle K...,0,-204.0,-69.0,61.0,114.0,10
40,C3,<AN>Männer</AN>,<RN>Professorinnen</RN>,True,53.0,4.0,<AN>Männer</AN>,135.0,-65.0,70.0,...,-173.0,-120.0,1,Im Rahmen einer öffentlichen Veranstaltung wir...,0,70.0,205.0,61.0,114.0,9
36,C4,<AN>Frauen</AN>,<RN>Expertinnen</RN>,True,53.0,4.0,<AN>Frauen</AN>,132.0,-63.0,69.0,...,-56.0,-3.0,1,Im Rahmen einer universitären Veranstaltung we...,0,69.0,201.0,61.0,114.0,7
34,C4,<AN>Frauen</AN>,<RN>Krankenschwestern</RN>,True,53.0,4.0,<AN>Frauen</AN>,132.0,-131.0,1.0,...,-173.0,-120.0,1,Bei einer Informationsveranstaltung im Kranken...,0,1.0,133.0,61.0,114.0,6
94,C4,<AN>Frauen</AN>,<RN>Unternehmerinnen</RN>,True,53.0,4.0,<AN>Frauen</AN>,132.0,-84.0,48.0,...,-56.0,-3.0,1,Bei einem Networking-Event stehen wirtschaftsp...,0,48.0,180.0,61.0,114.0,13
31,C5,<AN>Männer</AN>,<RN>Arbeitnehmer*innen</RN>,True,53.0,4.0,<AN>Männer</AN>,135.0,-220.0,-85.0,...,-56.0,-3.0,1,Im Rahmen einer Geschäftsveranstaltung findet ...,0,-85.0,50.0,61.0,114.0,5
20,C5,<AN>Männer</AN>,<RN>Aktivist*innen</RN>,True,53.0,4.0,<AN>Männer</AN>,135.0,-201.0,-66.0,...,-173.0,-120.0,1,Auf einer öffentlichen Veranstaltung werden ak...,0,-66.0,69.0,61.0,114.0,4
38,C5,<AN>Männer</AN>,<RN>Ingenieur*innen</RN>,True,53.0,4.0,<AN>Männer</AN>,135.0,365.0,500.0,...,-56.0,-3.0,1,Im Rahmen einer städtischen Planungsrunde wird...,0,500.0,635.0,61.0,114.0,8
15,C6,<AN>Frauen</AN>,<RN>Polizist*innen</RN>,True,53.0,4.0,<AN>Frauen</AN>,132.0,-202.0,-70.0,...,-173.0,-120.0,1,Bei einer öffentlichen Sitzung im Rathaus wird...,0,-70.0,62.0,61.0,114.0,2
100,C6,<AN>Frauen</AN>,<RN>Arbeitnehmer*innen</RN>,True,53.0,4.0,<AN>Frauen</AN>,132.0,-105.0,27.0,...,-56.0,-3.0,1,Auf einer Gewerkschaftsveranstaltung wird derz...,0,27.0,159.0,61.0,114.0,16
106,C6,<AN>Frauen</AN>,<RN>Lehrer*innen</RN>,True,53.0,4.0,<AN>Frauen</AN>,132.0,-333.0,-201.0,...,-173.0,-120.0,1,Auf einer Konferenz zu Bildungsfragen wird der...,0,-201.0,-69.0,61.0,114.0,18